### ISSUE TITLE
Install do not have the JS folder

### ISSUE THREAD

**Issue by jmbertoncelli** [CermakM/jupyter-datatables#3]
Javascript folder is not deployed when using pip then jupyter install, enable....

thank you.

**Comment by CermakM** [comment]
Hello @jmbertoncelli,

Thanks for pointing that out! It was indeed missing from the setup script.

This should be fixed by https://github.com/CermakM/jupyter-datatables/commit/5333898ab3a7f851c4a0483a80f8eeeec54cdbac and will be present in `0.2.0`

**Comment by toddrme2178** [comment]
I am looking at the sdist for 0.2.0 and the `js` and `css` directories are still missing.
